# Copyright (c) 2024 Cisco and/or its affiliates.

# This software is licensed to you under the terms of the Cisco Sample
# Code License, Version 1.1 (the "License"). You may obtain a copy of the
# License at

#                https://developer.cisco.com/docs/licenses

# All use of the material herein must be in accordance with the terms of
# the License. All rights not expressly granted by the License are
# reserved. Unless required by applicable law or agreed to separately in
# writing, software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.
---
- hosts: meraki_tag_catalyst_switch
  connection: network_cli
  vars_files:
    - vars/vars.yml
    - vars/cred.yml
  gather_facts: no
  tasks:
    - name: Check if host-specific variables file exists
      stat:
        path: "hosts_vars/l2/{{ inventory_hostname }}.yml"
      register: host_specific_var_file

    - name: Set fact if host-specific variables file exists
      set_fact:
        ansible_local:
          host_specific_var_file_exists: "{{ host_specific_var_file.stat.exists }}"

    - name: Include default variables from external file
      include_vars:
        file: vars/l2.yml
      when: inventory_hostname in groups['meraki_tag_catalyst_switch'] and not ansible_local.host_specific_var_file_exists|default(false)

    - name: Include host-specific variables if available
      include_vars:
        file: "host_vars/l2/{{ inventory_hostname }}.yml"
      when:
        - inventory_hostname in groups['meraki_tag_catalyst_switch']
        - ansible_local.host_specific_var_file_exists|default(false)

    - name: Merge VLAN interface configuration
      cisco.ios.ios_l2_interfaces:
        config:
          - name: "{{ item.name }}"
            mode: "{{ item.mode }}"
            access:
              vlan: "{{ item.access.vlan | default(omit) }}"
            voice:
              vlan: "{{ item.voice.vlan | default(omit) }}"
            trunk:
              allowed_vlans: "{{ item.trunk.allowed_vlans | default(omit) }}"
              native_vlan: "{{ item.trunk.native_vlan | default(omit) }}"
        state: replaced
      loop: "{{ interfaces }}"
      when: inventory_hostname in groups['meraki_tag_catalyst_switch']

    - name: Merge interface configuration
      cisco.ios.ios_interfaces:
        config:
          - name: "{{ item.name }}"
            description: "{{ item.description }}"
            enabled: "{{ item.enabled }}"
        state: replaced
      loop: "{{ interfaces }}"
      when: inventory_hostname in groups['meraki_tag_catalyst_switch']
