# Copyright (c) 2024 Cisco and/or its affiliates.

# This software is licensed to you under the terms of the Cisco Sample
# Code License, Version 1.1 (the "License"). You may obtain a copy of the
# License at

#                https://developer.cisco.com/docs/licenses

# All use of the material herein must be in accordance with the terms of
# the License. All rights not expressly granted by the License are
# reserved. Unless required by applicable law or agreed to separately in
# writing, software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.
---
- hosts: meraki_tag_catalyst_switch
  connection: network_cli
  vars_files:
    - vars/vars.yml
  gather_facts: no
  tasks:
    - name: Run show version and parse
      ansible.utils.cli_parse:
        command: "show version"
        parser:
          name: ansible.netcommon.pyats
        set_fact: versions_fact
    - name: Show version info
      debug:
        msg: "The OS is {{ versions_fact.version.os }} and the version is {{ versions_fact.version.version }}"
