# Copyright (c) 2024 Cisco and/or its affiliates.

# This software is licensed to you under the terms of the Cisco Sample
# Code License, Version 1.1 (the "License"). You may obtain a copy of the
# License at

#                https://developer.cisco.com/docs/licenses

# All use of the material herein must be in accordance with the terms of
# the License. All rights not expressly granted by the License are
# reserved. Unless required by applicable law or agreed to separately in
# writing, software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.
---
- hosts: meraki_tag_catalyst_switch
  connection: network_cli
  vars_files:
    - vars/vars.yml
  gather_facts: no
  vars:
    ansible_verbosity: 2 # Set the default verbosity level here
  tasks:
    - name: Check if host-specific variables file exists
      stat:
        path: "host_vars/vlans/{{ inventory_hostname }}.yml"
      register: host_specific_var_file

    - name: Set fact if host-specific variables file exists
      set_fact:
        ansible_local:
          host_specific_var_file_exists: "{{ host_specific_var_file.stat.exists }}"

    - name: Include default variables from external file
      include_vars:
        file: vars/vlans.yml
      when: inventory_hostname in groups['meraki_tag_catalyst_switch'] and not ansible_local.host_specific_var_file_exists|default(false)

    - name: Include host-specific variables if available
      include_vars:
        file: "host_vars/vlans/{{ inventory_hostname }}.yml"
      when:
        - inventory_hostname in groups['meraki_tag_catalyst_switch']
        - ansible_local.host_specific_var_file_exists|default(false)

    - name: Run IOS VLANs query to override VLAN configuration
      ios_vlans:
        config: "{{ vlans }}"
        state: overridden
      register: ios_vlans_result
      ignore_errors: true

    - name: Retry task if it fails a second time
      when: ios_vlans_result is failed
      block:
        - name: Run IOS VLANs query a second time
          ios_vlans:
            config: "{{ vlans }}"
            state: overridden
